### ISSUE TITLE
Few small issues

### ISSUE THREAD

**Issue by SinisterSpatula** [raminsamadi123/hyprinstall#4]
Your install script works great!  Just a few small issues I have:
ctrl+x in nano editor is instead triggering 'copy mode' in hyprland, but I don't see any binding in hyprland.conf for ctrl+x?
~~Filemanager (super + E) doesn't seem to launch~~ (edit: for some reason thunar didn't install, I installed thunar and got that working now).
~~Is it possible to drag the tiled windows around with the mouse? (I currently can't move them without keyboard).~~ edit: hold super key (windows key) and click and drag mouse to move the window.
~~keyboard language, how can I switch that to US-english?~~ edit: I found the info in your instructions and the hyprwiki.
~~I have multiple monitors and need to set their physical placement differently (I need to tell hyprland that the second monitor is to the left of the primary, not to the right of it).  Any hints how to switch that?~~ edit: I figured this out too (below).

**Comment by SinisterSpatula** [comment]
Ah I see, I need to edit ~/.config/hypr/hyprland.conf and change language from 'se' to 'us'.  And I need to read the hyprland wiki :)
To help others: I had to use wlr-randr to find that my monitors are on DP-5 and DP-6 (they're connected through my intel iGPU using daisychaining aka DP MST).  I used these settings to get close to what I need:
```
#monitor=name, resolution, position, scale
monitor=DP-5, 2560x1440, 1920x0, 1.25
monitor=DP-6, 1920x1080, 0x0, 1
```

**Comment by mainmast-git** [comment]
Hello @SinisterSpatula yes everything you said was not really an issue. I decided to not install Thunar, file-roller, archive manager, etc or a browser so that the user is free to choose it by themselves. The only issue is nano for some reason. I experienced that as well. But have no clue what is causing it. I mostly used vim so I didn't try to fix it. Thanks for letting me know 😁👍

**Comment by mainmast-git** [comment]
I have now added your issues in my README.md so that others may find a solution to your problems. Thanks 🙏
