### ISSUE TITLE
Black screen after GRUB

### ISSUE THREAD

**Issue by QuantumKuba** [raminsamadi123/hyprinstall#6]
After installation the first reboot it goes through grub but after it results in a black screen with just my motherboards logo showing. 

The only option after that is a reboot. 

During the Arch install I selected sway, ext4, pipewire, multilib and for the graphics drivers I've left if on default which installed all open source.

My setup:
Nvidia GTX 1080ti
i7-4790k
Gigabyte z97x

**Comment by mainmast-git** [comment]
Hmm, have you tried to change the boot order or select another boot device manually in your motherboard’s UEFI?

**Comment by QuantumKuba** [comment]
Yes, I've tried both.
I don't think the issue is caused by the script itself.

I've tried to manually install hyprland and NVIDIA drivers using their documentation however same issue arises.

**Comment by mainmast-git** [comment]
Try using the command journalctl -Xe or just journalctl when being in the tty you can access it by pressing Ctrl + Alt + F2 and then login to your user or root and watch your logs to see if anything suspicious happens when starting hyprland.
