### ISSUE TITLE
Dual GPU scenario

### ISSUE THREAD

**Issue by D3vil0p3r** [raminsamadi123/hyprinstall#8]
I'm testing your settings and they seem very cool!

The NVIDIA scenario works only for computers with one GPU.

Nowadays a lot of computers have CPU with Integrated GPU and the NVIDIA settings explained in the README don't work because in that manner we are forcing NVIDIA variable values when the computer is using (by default) the Integrated GPU.

Did you already explore the settings scenario with Integrated GPU (e.g., Intel GPU) and NVIDIA GPU together?

**Comment by mainmast-git** [comment]
Hello @D3vil0p3r,
No, I have not explored the settings scenario with an Integrated GPU (e.g., Intel GPU) and NVIDIA GPU together. Currently, I am using an old desktop with an `NVIDIA Geforce GTX 745` PCIE x16 graphics card, so the NVIDIA settings explained in the README don't apply to my setup. However, if you require assistance or have any specific questions regarding your scenario, I'll be glad to help to the best of my abilities.

Best regards,
@raminsamadi123

**Comment by D3vil0p3r** [comment]
Thank you mate.

**Comment by D3vil0p3r** [comment]
@raminsamadi123  why those settings don't apply on your configuration if you have only NVIDIA GPU? I expect it should work.
